### PR TITLE
WIP: Set up CI with Azure Pipelines

### PR DESCRIPTION
**Pull request by JuanSeBestia**

### CODE REVIEW

**Comment by JuanSeBestia** [comment]
Now you can see the tests results, summary and coverage in AzureDevOps

image

image

image

**Comment by JuanSeBestia** [comment]
@jlcasasg , you can see in https://dev.azure.com/juansecloud/

**Comment by JuanSeBestia** [comment]
change karma to run inside CI
change protactor to run inside CI

**Comment by JuanSeBestia** [comment]
image

**Comment by JuanSeBestia** [comment]
image

**Comment by jlcasasg** [comment]
image
can you give me access to jesik-94@hotmail.com email?

**Comment by jlcasasg** [comment]
@JuanSeBestia There is a file conflict

**Comment by JuanSeBestia** [comment]
Conlficts solved

**Comment by JuanSeBestia** [comment]
This PR solve the issue #15

**Comment by jlcasasg** [comment]
still with conflicts...

**Comment by JuanSeBestia** [comment]
Fuck

**Comment by JuanSeBestia** [comment]
I resolve the conflicts, @jlcasasg please prove again

**Pull request merged**
