### PR TITLE
Style (US-2): Update large view screens

### PR DESCRIPTION
**Pull request by JessCasasDev**

### CODE REVIEW

**Comment by JuanSeBestia** [comment]
I fix something in build related of environments in #49, please check it

**Comment by JuanSeBestia** [comment]
Lint a Unit-test failing, please fix them

**Comment by JessCasasDev** [comment]
done

**Review by JuanSeBestia — APPROVED** [review]

**Comment by JuanSeBestia** [comment]
Unit test failed :P

**Comment by JessCasasDev** [comment]
ya

**Comment by JuanSeBestia** [comment]
Raios my fault has a deploy error :(

**Pull request merged**
